#===============================================================================
# @brief    Application Core LOG Software Module KV Pair Definitions
# Copyright (c) 2018 Huawei Technologies Co. Ltd
#===============================================================================

- entry: kv_definitions
  version: 0.1
  core: application
  module: LWM2M
  module_id: 128
  key_definitions:

  - key_id: 32768
    key_status: alive
    key_name: NV_DATA_MODE
    description: Key NV_DATA_MODE description
    structure_type: PIN

  - key_id: 32769
    key_status: alive
    key_name: LWM2M_BS_PARA
    description: Key LWM2M_BS_PARA description
    structure_type: PIN

  - key_id: 32770
    key_status: alive
    key_name: LWM2M_BS_MODE
    description: Key LWM2M_BS_MODE description
    structure_type: NEUL_LOG_LEVEL

  - key_id: 32771
    key_status: alive
    key_name: LWM2M_FOTA_IND
    description: Key LWM2M_FOTA_IND description
    structure_type: PIN

  - key_id: 32772
    key_status: alive
    key_name: LWM2M_SELFCURE_REG
    description: Key LWM2M_SELFCURE_REG description
    structure_type: PIN

  - key_id: 32773
    key_status: alive
    key_name: LWM2M_CDP_IPV4
    description: Key LWM2M_CDP_IPV4 description
    structure_type: PIN
    
  - key_id: 32774
    key_status: alive
    key_name: LWM2M_CDP_PORT
    description: Key LWM2M_CDP_PORT description
    structure_type: PIN

  - key_id: 32775
    key_status: alive
    key_name: LWM2M_CDP_ID
    description: Key LWM2M_CDP_ID description
    structure_type: PIN

  - key_id: 32776
    key_status: alive
    key_name: LWM2M_REG_SWT
    description: Key LWM2M_REG_SWT description
    structure_type: PIN
    
  - key_id: 32777
    key_status: alive
    key_name: LWM2M_CDP_IP
    description: Key LWM2M_CDP_IP description
    structure_type: PIN

  - key_id: 32778
    key_status: alive
    key_name: LWM2M_CLINENT_HOLD_OFF_TIMER
    description: Key LWM2M_CLINENT_HOLD_OFF_TIMER description
    structure_type: PIN

  - key_id: 32779
    key_status: alive
    key_name: LWM2M_BOOTSTRAP_SERVER_IP
    description: Key LWM2M_BOOTSTRAP_SERVER_IP description
    structure_type: PIN
  
  - key_id: 32780
    key_status: alive
    key_name: LWM2M_BOOTSTRAP_SERVER_PORT
    description: Key LWM2M_BOOTSTRAP_SERVER_PORT description
    structure_type: PIN

  - key_id: 32781
    key_status: alive
    key_name: LWM2M_CDP_NEW_IP
    description: Key LWM2M_CDP_NEW_IP description
    structure_type: PIN

  - key_id: 32782
    key_status: alive
    key_name: LWM2M_CDP_NEW_PORT
    description: Key LWM2M_CDP_NEW_PORT description
    structure_type: PIN
    
  - key_id: 32783
    key_status: alive
    key_name: LWM2M_SHORT_SERVERID
    description: Key LWM2M_SHORT_SERVERID description
    structure_type: PIN

  - key_id: 32784
    key_status: alive
    key_name: LWM2M_REMOTE_CONFIG_FLAG
    description: Key LWM2M_REMOTE_CONFIG_FLAG description
    structure_type: PIN

  - key_id: 32785
    key_status: alive
    key_name: LWM2M_CDP_DOMAIN
    description: Key LWM2M_CDP_DOMAIN description
    structure_type: PIN

  - key_id: 32786
    key_status: alive
    key_name: LWM2M_ENABLE_FLAG
    description: Key LWM2M_ENABLE_FLAG description
    structure_type: PIN

  - key_id: 32787
    key_status: alive
    key_name: LWM2M_TYPE_UPLOAD_RESULT
    description: Key LWM2M_TYPE_UPLOAD_RESULT description
    structure_type: PIN

  - key_id: 32788
    key_status: alive
    key_name: LWM2M_NEW_MESSAGE_ID
    description: Key LWM2M_NEW_MESSAGE_ID description
    structure_type: PIN
    
  - key_id: 32789
    key_status: alive
    key_name: LWM2M_LIFETIME_SWT
    description: Key LWM2M_LIFETIME_SWT description
    structure_type: PIN
    
