#===============================================================================
# @brief    Application Core LOG Software Module KV Pair Definitions
# Copyright (c) 2018 Huawei Technologies Co. Ltd
#===============================================================================

- entry: kv_definitions
  version: 0.1
  core: application
  module: DNS
  module_id: 132
  key_definitions:

  - key_id: 33792
    key_status: alive
    key_name: DNS_INFO1
    description: Key DNS_INFO1 description
    structure_type: PIN

  - key_id: 33793
    key_status: alive
    key_name: DNS_INFO2
    description: Key DNS_INFO2 description
    structure_type: PIN

  - key_id: 33794
    key_status: alive
    key_name: DNS_INFO3
    description: Key DNS_INFO3 description
    structure_type: PIN

  - key_id: 33795
    key_status: alive
    key_name: DNS_INFO4
    description: Key DNS_INFO4 description
    structure_type: PIN

  - key_id: 33796
    key_status: alive
    key_name: DNS_INFO5
    description: Key DNS_INFO5 description
    structure_type: PIN

  - key_id: 33797
    key_status: alive
    key_name: DNS_INFO6
    description: Key DNS_INFO6 description
    structure_type: PIN
