#===============================================================================
# @brief    Application Core LWIP_SUPPORT Software Module KV Pair Definitions
# Copyright (c) 2018 Huawei Technologies Co. Ltd
#===============================================================================

- entry: kv_definitions
  version: 0.1
  core: application
  module: LWIP_SUPPORT
  module_id: 1
  key_definitions: []
