#===============================================================================
# @brief    Application Core OTA Software Module KV Pair Definitions
# Copyright (c) 2018 Huawei Technologies Co. Ltd
#===============================================================================

- entry: kv_definitions
  version: 0.1
  core: application
  module: OTA
  module_id: 20
  key_definitions:

  - key_id: 5120
    key_status: reserved
    key_name: OTA_KEYID_UPDATE_STATE
    description: Key OTA_KEYID_UPDATE_STATE description
    structure_type: uint8

  - key_id: 5121
    key_status: reserved
    key_name: OTA_KEYID_UPDATE_RESULT
    description: Key OTA_KEYID_UPDATE_RESULT description
    structure_type: uint8

  - key_id: 5122
    key_status: reserved
    key_name: OTA_KEYID_UPDATE_TOKEN
    description: Key OTA_KEYID_UPDATE_TOKEN description
    structure_type: str_token

  - key_id: 5123
    key_status: reserved
    key_name: OTA_KEYID_UPDATE_MODE
    description: Key OTA_KEYID_UPDATE_MODE description
    structure_type: uint8

