#===============================================================================
# @brief    Application Core Software Module Definitions
# Copyright (c) 2018 Huawei Technologies Co. Ltd
#===============================================================================

#
# Software Modules numberspace is divided:
#   - module ids 0-95: Neul/Huawei
#   - module ids 96-132: RDK
#   - module ids 133-255: customer configurable
#

- entry: module_definitions
  version: 0.1
  core: application
  module_definitions:

  # Neul/Huawei modules(0-95):
  - module_id: 0
    module_name: BASE
    module_description: Module BASE description
  - module_id: 1
    module_name: LWIP_SUPPORT
    module_description: Module LWIP_SUPPORT description
  # Module ID 4 should not be used!
  - module_id: 8
    module_name: AT
    module_description: Module AT description
  - module_id: 12
    module_name: LOG
    module_description: Module LOG description
  # Module ID 16 should not be used!
  - module_id: 20
    module_name: OTA
    module_description: Module OTA description
  - module_id: 24
    module_name: UNUSED
    module_description: Module UNUSED description
  - module_id: 28
    module_name: NETWORK
    module_description: Module NETWORK description

