#===============================================================================
# @brief    Application Core BASE Software Module KV Pair Definitions
# Copyright (c) 2018 Huawei Technologies Co. Ltd
#===============================================================================

- entry: kv_definitions
  version: 0.1
  core: application
  module: BASE
  module_id: 0
  key_definitions:

  - key_id: 0
    key_status: deprecated
    key_name: BASE_KEYID_DEPRECATED_DO_NOT_USE
    description: Key BASE_KEYID_DEPRECATED_DO_NOT_USE description
    structure_type: UNDETERMINED_SIZE_BUFFER

  - key_id: 1
    key_status: alive
    key_name: BASE_KEYID_SPI_CLK_PIN
    description: Key BASE_KEYID_SPI_CLK_PIN description
    structure_type: PIN

  - key_id: 2
    key_status: alive
    key_name: BASE_KEYID_SPI_MISO_PIN
    description: Key BASE_KEYID_SPI_MISO_PIN description
    structure_type: PIN

  - key_id: 3
    key_status: alive
    key_name: BASE_KEYID_SPI_MOSI_PIN
    description: Key BASE_KEYID_SPI_MOSI_PIN description
    structure_type: PIN

  - key_id: 4
    key_status: alive
    key_name: BASE_KEYID_SPI_MEM_CS_PIN
    description: Key BASE_KEYID_SPI_MEM_CS_PIN description
    structure_type: PIN

  - key_id: 5
    key_status: alive
    key_name: BASE_KEYID_FIXED_PINS
    description: Key BASE_KEYID_FIXED_PINS description
    structure_type: pin_map_buffer_t

  - key_id: 6
    key_status: alive
    key_name: BASE_KEYID_MANUFACTURER_IDENTIFIER
    description: Key BASE_KEYID_MANUFACTURER_IDENTIFIER description
    structure_type: UNDETERMINED_SIZE_STRING

  - key_id: 7
    key_status: alive
    key_name: BASE_KEYID_MANUFACTURER_MODEL_IDENTIFIER
    description: Key BASE_KEYID_MANUFACTURER_MODEL_IDENTIFIER description
    structure_type: UNDETERMINED_SIZE_STRING

  - key_id: 8
    key_status: alive
    key_name: BASE_KEYID_ACTIVITY_INDICATION_PIN
    description: Key BASE_KEYID_ACTIVITY_INDICATION_PIN description
    structure_type: PIN

  - key_id: 9
    key_status: alive
    key_name: BASE_KEYID_ACTIVITY_INDICATION_DELAY_MILLISECONDS
    description: Key BASE_KEYID_ACTIVITY_INDICATION_DELAY_MILLISECONDS description
    structure_type: activity_indication_delay_milliseconds_t

  - key_id: 10
    key_status: alive
    key_name: BASE_KEYID_VDD_IO_BANK_R2
    description: Key BASE_KEYID_VDD_IO_BANK_R2 description
    structure_type: PMU_VDD_IO_LEVEL

  - key_id: 11
    key_status: alive
    key_name: BASE_KEYID_VDD_IO_BANK_L1
    description: Key BASE_KEYID_VDD_IO_BANK_L1 description
    structure_type: PMU_VDD_IO_LEVEL

  - key_id: 12
    key_status: alive
    key_name: BASE_KEYID_I2C_SCL_PIN
    description: Key BASE_KEYID_I2C_SCL_PIN description
    structure_type: PIN

  - key_id: 13
    key_status: alive
    key_name: BASE_KEYID_I2C_SDA_PIN
    description: Key BASE_KEYID_I2C_SDA_PIN description
    structure_type: PIN

# Replaced by the combined BASE_KEYID_UART_0_CONFIG, below
  - key_id: 14
    key_status: deprecated
    key_name: BASE_KEYID_PRIMARY_UART_CTS_PIN
    description: Key BASE_KEYID_PRIMARY_UART_CTS_PIN description
    structure_type: PIN

# Replaced by the combined BASE_KEYID_UART_0_CONFIG, below
  - key_id: 15
    key_status: deprecated
    key_name: BASE_KEYID_PRIMARY_UART_RTS_PIN
    description: Key BASE_KEYID_PRIMARY_UART_RTS_PIN description
    structure_type: PIN
    
  - key_id: 16
    key_status: alive
    key_name: BASE_KEYID_UART_0_CONFIG
    description: Define the pins used for UART 0
    structure_type: uart_pin_configuration

  - key_id: 17
    key_status: alive
    key_name: BASE_KEYID_UART_1_CONFIG
    description: Define the pins used for UART 1
    structure_type: uart_pin_configuration

