#===============================================================================
# @brief    Application Core LOG Software Module KV Pair Definitions
# Copyright (c) 2018 Huawei Technologies Co. Ltd
#===============================================================================

- entry: kv_definitions
  version: 0.1
  core: application
  module: LOG
  module_id: 12
  key_definitions:

# Replaced by the combined BASE_KEYID_UART_1_CONFIG, in application_core_platform_config.yml, as part of the hardware configuration!
  - key_id: 3072
    key_status: deprecated
    key_name: LOG_KEYID_UART_TX_PIN
    description: Key LOG_KEYID_UART_TX_PIN description
    structure_type: PIN

  - key_id: 3073
    key_status: alive
    key_name: LOG_KEYID_NXLOG_CONFIG
    description: Key LOG_KEYID_NXLOG_CONFIG description
    structure_type: bool

  - key_id: 3074
    key_status: alive
    key_name: LOG_KEYID_LOG_LEVEL
    description: Key LOG_KEYID_LOG_LEVEL description
    structure_type: NEUL_LOG_LEVEL

