#===============================================================================
# @brief    Application Core LOG Software Module KV Pair Definitions
# Copyright (c) 2018 Huawei Technologies Co. Ltd
#===============================================================================

- entry: kv_definitions
  version: 0.1
  core: application
  module: LCGMR
  module_id: 134
  key_definitions:

  - key_id: 34304
    key_status: alive
    key_name: LCGMR_INFO
    description: Key LCGMR_INFO description
    structure_type: UNDETERMINED_SIZE_STRING
 